# Generated by Django 3.1 on 2023-01-20 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loginsign.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('name', models.CharField(max_length=30)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('resume', models.FileField(blank=True, null=True, upload_to=loginsign.models.path_and_rename_for_resume)),
                ('industry', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiledetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
